version: '3.9'

services:
  # postgres:
  #  image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: kasra123
  #     POSTGRES_DB: nftboxnew
  #   ports:
  #     - 5431:5432
  #   volumes:
  #     - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
#volumes:
#  postgres_volume:
#    driver: local
